### PR TITLE
Bug fixing

### LINKED ISSUE #22: Bug fixing
List of corrections:

https://github.com/stadtluzern/decidim-letterbox-damagereporting/issues/9
- [ ] "choose file" button: open standard file chooser
- [x] "upload picture": work as it does now
- [ ] Attachments section: does not have the upload picture

https://github.com/stadtluzern/decidim-letterbox-damagereporting/issues/10
- [ ] After adding an address, if choose to check the "has no address" checkbox, the existing address should disappear along with any errors

https://github.com/stadtluzern/decidim-letterbox-damagereporting/issues/37
- [ ]  Step 4 out of 3 (see the issue, there's a edge case where it seems that there are 4 steps).
- [x]  View of old format proposals when you modify your proposal: The edit form should be the same as the "new" form

### PR DESCRIPTION
**Pull request by antopalidi**
fixes #22

### CODE REVIEW

File: app/controllers/concerns/decidim/reporting_proposals/proposals_controller_override.rb [hunk 1]
```diff
@@ -49,8 +49,19 @@ def complete
...
+        def edit_form
+          form_attachment_model = form(AttachmentForm).from_model(@proposal.attachments.first)
+          @form = form_reporting_proposals_model
+          @form.attachment = form_attachment_model
+          @form
+        end
+
         private
 
+        def form_reporting_proposals_model
```
Comment (microstudi) [inline app/controllers/concerns/decidim/reporting_proposals/proposals_controller_override.rb:61]:
```suggestion
        def form_proposal_model
```
If we override the original method, we don't need to override the method `edit_form`

File: app/controllers/concerns/decidim/reporting_proposals/proposals_controller_override.rb [hunk 2]
```diff
@@ -49,8 +49,19 @@ def complete
           redirect_to "#{Decidim::ResourceLocatorPresenter.new(@proposal).path}/preview" if reporting_proposal?
         end
 
+        def edit_form
+          form_attachment_model = form(AttachmentForm).from_model(@proposal.attachments.first)
+          @form = form_reporting_proposals_model
+          @form.attachment = form_attachment_model
+          @form
+        end
+
```
Comment (microstudi) [inline app/controllers/concerns/decidim/reporting_proposals/proposals_controller_override.rb:58]:
```suggestion
```
I think we can skip this override if we rename  `form_reporting_proposals_model` to `form_proposal_model`

**Review by microstudi — CHANGES_REQUESTED** [review]
Hi, 
I think we should do thinks a little bit differently here.

One thing is that we should reuse the current partial `_reporting_proposal_fields.html.erb` for creating and for editing a reporting proposals.

Therefore, instead of overriding the partial `_edit_form_fields.html.erb` we should override the files `edit.html.erb` and `edit_draft.html.erb` and change this content:

```erb
<%= render partial: "edit_form_fields", locals: { form: form } %>
```

For something like:

```erb
<%= render "decidim/reporting_proposals/proposals/#{reporting_proposal? ? 'edit_draft_proposal_fields' : 'edit_form_fields'}", form: form %>
```
Replacing the javascript part too if necessary.

File: app/controllers/concerns/decidim/reporting_proposals/proposals_controller_override.rb (hunk 2 above)
Comment (antopalidi) [reply app/controllers/concerns/decidim/reporting_proposals/proposals_controller_override.rb:58]: If I don't override this method, then has_no_image will be undefined, because has_no_image is not in Decidim::Proposals::ProposalForm

File: app/overrides/decidim/proposals/proposals/edit_draft/replace_partial_edit_form_fields.html.erb.deface [hunk 3]
```diff
@@ -0,0 +1,3 @@
+<!-- replace "erb[loud]:contains('edit_form_fields')" -->
+
+<%= render "decidim/reporting_proposals/proposals/#{reporting_proposal? ? 'reporting_proposal_fields' : 'edit_form'}", form: form %>
```
Comment (microstudi) [inline app/overrides/decidim/proposals/proposals/edit_draft/replace_partial_edit_form_fields.html.erb.deface:3]:
```suggestion
<%= render "decidim/#{reporting_proposal? ? reporting_proposals' : 'proposals'}/proposals/edit_form", form: form %>
```
I think in here we want to use the original form when the proposals is a normal one, and our editor when is a reporting proposal

**Review by microstudi — CHANGES_REQUESTED** [review]
I still see that we are overriding the view for normal proposals, this is not necessary.
Tomorrow we will be a little bit more specific

File: app/overrides/decidim/proposals/proposals/edit_draft/replace_partial_edit_form_fields.html.erb.deface (hunk 3 above)
Comment (antopalidi) [reply app/overrides/decidim/proposals/proposals/edit_draft/replace_partial_edit_form_fields.html.erb.deface]: Yes, I corrected a few deface files. Now the original form is not overridden

File: app/controllers/concerns/decidim/reporting_proposals/proposals_controller_override.rb (hunk 2 above)
Comment (antopalidi) [reply app/controllers/concerns/decidim/reporting_proposals/proposals_controller_override.rb]: Of course. The component check is in the method `form_proposal_model`. 
I may not add a new method, but use a method with the same name as the one already defined in `edit_form`.

Changed

**Review by microstudi — CHANGES_REQUESTED** [review]
Thanks @antopalidi, good work but we still need to fix some thinks:

image

1. [ ] In here, while editing a proposal (when editing a draft for instance) we see "step 3 of 3", it should be "step 1 of 3".

2. [ ] In the "upload image" section, the button "choose file" should open the file picker in the mobile, while the button "use my camera" should open the camera directly.

image

image

3. [ ] The camera input in the attachment shouldn't be here (deactivate "use only photo attachments" to see it). The "choose file" should open the file picker in the phone.

[errors_location.webm](https://user-images.githubusercontent.com/1401520/197997864-50f40d56-987c-48c0-b6ce-1214747bd3f1.webm)

4. [x] the gelocation section should be improved, specially, if you click "no address", then the button for "my location" should be deactivated and the errors and current address removed.

5. [ ] When editing a reporting proposal, the fields "has no image" and "has no address" are not remembered.

6. [ ] We need to add some tests to cover the diferences when editing a reporting proposal and a a normal proposal, ensure that everything works as expected

File: spec/system/shared/proposals_steps_examples.rb [hunk 4]
```diff
@@ -149,6 +152,15 @@
...
+    fill_proposal(skip_address: true, attach: false)
+
+    click_link "Modify the proposal"
+
+    expect(page).to have_css(".user-device-location button[disabled]")
+    expect(page).to have_css("button.user-device-camera[disabled]")
+  end
 end
 
 shared_examples "4 steps" do
```
Comment (microstudi) [inline spec/system/shared/proposals_steps_examples.rb:166]: In this example we should add some cases checking that editing a normal proposal / either draft or the normal one has no changes due the deface overridades.

File: app/overrides/decidim/proposals/proposals/edit/remove_title.html.erb.deface [hunk 5]
```diff
@@ -0,0 +1 @@
+<!-- remove ".hashtags__container" -->
```
Comment (microstudi) [inline app/overrides/decidim/proposals/proposals/edit/remove_title.html.erb.deface:1]: Do we need this deface entry? I don't see any `.hashtags__container" in the `edit.html.erb`

File: app/overrides/decidim/proposals/proposals/edit_draft/remove_title.html.erb.deface [hunk 6]
```diff
@@ -0,0 +1 @@
+<!-- remove ".hashtags__container" -->
```
Comment (microstudi) [inline app/overrides/decidim/proposals/proposals/edit_draft/remove_title.html.erb.deface:1]: Same as before, why we need this?

File: app/views/decidim/reporting_proposals/proposals/_edit_form_fields.html.erb [hunk 7]
```diff
@@ -0,0 +1,7 @@
+<div class="field hashtags__container">
```
Comment (microstudi) [inline app/views/decidim/reporting_proposals/proposals/_edit_form_fields.html.erb:1]: I think this file is not used at all, can we remove it? or I missed something?

**Review by microstudi — CHANGES_REQUESTED** [review]
Thanks @antopalidi 

this is almost finished, I have some doubts about of the files that does not seem to be used at all (see the comments).
And, finally, we need to add an extra test case for the normal proposals to check there's nothing overriden there.

proposals/proposals/edit.html.erb
proposals/proposals/edit_draft.html.erb
proposals/proposals/_edit_form_fields.html.erb
